# 数据库的默认账号和密码仅首次运行时设置有效
version: '3.3'
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql-agentflow
    restart: always
    ports:
      - 3306:3306
    environment:
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: mysqlagentflow
      MYSQL_DATABASE: agentflow
    volumes:
      - ./mysql:/var/lib/mysql


      